import PDFDocument from 'pdfkit';

export const generateTicketPDF = async (registration, event, organizer) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A5', margin: 30 });
      const chunks = [];
      
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      
      // Header
      doc.fillColor('#431E7A').fontSize(20).text(process.env.PLATFORM_NAME || 'EventHub', { align: 'center' });
      doc.moveDown(0.3);
      doc.fillColor('#71717A').fontSize(9).text(process.env.PLATFORM_TAGLINE || 'Register. Attend. Connect.', { align: 'center' });
      
      // Divider
      doc.moveDown(0.5);
      doc.strokeColor('#6C3BAA').lineWidth(1).moveTo(30, doc.y).lineTo(doc.page.width - 30, doc.y).stroke();
      doc.moveDown(0.5);
      
      // Event Title
      doc.fillColor('#431E7A').fontSize(16).text(event.title, { align: 'center' });
      doc.moveDown(0.3);
      doc.fillColor('#71717A').fontSize(9).text(`Organized by ${organizer?.organization || organizer?.fullName || 'Event Organizer'}`, { align: 'center' });
      
      doc.moveDown(0.8);
      
      // Ticket Number
      doc.fillColor('#E8472A').fontSize(22).text(registration.ticketNumber, { align: 'center' });
      doc.fillColor('#71717A').fontSize(8).text('TICKET NUMBER', { align: 'center' });
      
      doc.moveDown(0.8);
      
      // Participant Info
      doc.fillColor('#27272A').fontSize(11).text('Participant', 30);
      doc.fillColor('#3F3F46').fontSize(10).text(registration.fullName);
      doc.text(registration.email);
      if (registration.phone) doc.text(registration.phone);
      
      doc.moveDown(0.5);
      
      // Event Details
      doc.fillColor('#27272A').fontSize(11).text('Event Details');
      doc.fillColor('#3F3F46').fontSize(9);
      doc.text(`Date: ${new Date(event.startDate).toLocaleDateString('en-GB')} ${event.startTime}`);
      doc.text(`Location: ${event.location}`);
      if (event.virtualLink) doc.text(`Virtual Link: ${event.virtualLink}`);
      doc.text(`Registration Code: ${registration.registrationCode}`);
      
      doc.moveDown(0.8);
      
      // Footer
      doc.strokeColor('#E4E4E7').lineWidth(0.5).moveTo(30, doc.y).lineTo(doc.page.width - 30, doc.y).stroke();
      doc.moveDown(0.3);
      doc.fillColor('#71717A').fontSize(8).text('Please present this ticket at the event entrance.', { align: 'center' });
      doc.text('Generated by EventHub', { align: 'center' });
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export const generateParticipantListPDF = async (event, registrations) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const chunks = [];
      
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      
      // Header
      doc.fillColor('#431E7A').fontSize(18).text('Participant List', { align: 'center' });
      doc.moveDown(0.3);
      doc.fillColor('#6C3BAA').fontSize(13).text(event.title, { align: 'center' });
      doc.moveDown(0.2);
      doc.fillColor('#71717A').fontSize(9).text(`Event Code: ${event.eventCode} | Date: ${new Date(event.startDate).toLocaleDateString('en-GB')}`, { align: 'center' });
      doc.moveDown(0.5);
      doc.strokeColor('#6C3BAA').lineWidth(1).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
      doc.moveDown(0.5);
      
      // Table Header
      const tableTop = doc.y;
      const cols = [
        { x: 40, label: 'Reg Code' },
        { x: 130, label: 'Name' },
        { x: 250, label: 'Email' },
        { x: 360, label: 'Phone' },
        { x: 430, label: 'Status' },
        { x: 490, label: 'Attendance' },
      ];
      
      doc.fillColor('#431E7A').fontSize(9);
      cols.forEach(col => doc.text(col.label, col.x, tableTop, { width: 80 }));
      
      doc.moveDown(0.5);
      doc.strokeColor('#E4E4E7').lineWidth(0.5).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
      doc.moveDown(0.3);
      
      // Rows
      doc.fillColor('#27272A').fontSize(8);
      registrations.forEach((reg, i) => {
        if (doc.y > doc.page.height - 60) {
          doc.addPage();
        }
        const y = doc.y;
        doc.text(reg.registrationCode, 40, y, { width: 90 });
        doc.text(reg.fullName, 130, y, { width: 120 });
        doc.text(reg.email, 250, y, { width: 110 });
        doc.text(reg.phone || '-', 360, y, { width: 70 });
        doc.text(reg.status, 430, y, { width: 60 });
        doc.text(reg.attendanceStatus, 490, y, { width: 60 });
        doc.moveDown(0.6);
      });
      
      // Total
      doc.moveDown(0.5);
      doc.strokeColor('#6C3BAA').lineWidth(1).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
      doc.moveDown(0.3);
      doc.fillColor('#431E7A').fontSize(10).text(`Total Registrations: ${registrations.length}`, { align: 'right' });
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export const generateAttendanceReportPDF = async (event, registrations) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const chunks = [];
      
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      
      const present = registrations.filter(r => r.attendanceStatus === 'Present').length;
      const absent = registrations.filter(r => r.attendanceStatus === 'Absent').length;
      const pending = registrations.filter(r => r.attendanceStatus === 'Pending').length;
      const total = registrations.length;
      const attendanceRate = total > 0 ? ((present / total) * 100).toFixed(1) : 0;
      
      // Header
      doc.fillColor('#431E7A').fontSize(18).text('Attendance Report', { align: 'center' });
      doc.moveDown(0.3);
      doc.fillColor('#6C3BAA').fontSize(13).text(event.title, { align: 'center' });
      doc.moveDown(0.2);
      doc.fillColor('#71717A').fontSize(9).text(`Generated: ${new Date().toLocaleString('en-GB')}`, { align: 'center' });
      doc.moveDown(0.5);
      doc.strokeColor('#6C3BAA').lineWidth(1).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
      doc.moveDown(0.8);
      
      // Summary
      doc.fillColor('#27272A').fontSize(12).text('Summary');
      doc.moveDown(0.3);
      doc.fillColor('#3F3F46').fontSize(10);
      doc.text(`Total Registered: ${total}`);
      doc.text(`Present: ${present}`);
      doc.text(`Absent: ${absent}`);
      doc.text(`Pending: ${pending}`);
      doc.text(`Attendance Rate: ${attendanceRate}%`);
      
      doc.moveDown(1);
      doc.fillColor('#27272A').fontSize(12).text('Detailed List');
      doc.moveDown(0.5);
      
      // Table
      const tableTop = doc.y;
      doc.fillColor('#431E7A').fontSize(9);
      doc.text('Name', 40, tableTop);
      doc.text('Email', 180, tableTop);
      doc.text('Status', 380, tableTop);
      
      doc.moveDown(0.5);
      doc.strokeColor('#E4E4E7').lineWidth(0.5).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
      doc.moveDown(0.3);
      
      doc.fillColor('#27272A').fontSize(8);
      registrations.forEach((reg) => {
        if (doc.y > doc.page.height - 60) doc.addPage();
        const y = doc.y;
        doc.text(reg.fullName, 40, y, { width: 140 });
        doc.text(reg.email, 180, y, { width: 200 });
        doc.text(reg.attendanceStatus, 380, y, { width: 100 });
        doc.moveDown(0.6);
      });
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export const generateSystemOverviewPDF = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const chunks = [];
      
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      
      doc.fillColor('#431E7A').fontSize(20).text('System Overview Report', { align: 'center' });
      doc.moveDown(0.3);
      doc.fillColor('#71717A').fontSize(10).text(`Generated: ${new Date().toLocaleString('en-GB')}`, { align: 'center' });
      doc.moveDown(0.8);
      doc.strokeColor('#6C3BAA').lineWidth(1).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
      doc.moveDown(0.8);
      
      // Summary Stats
      doc.fillColor('#27272A').fontSize(14).text('System Statistics');
      doc.moveDown(0.3);
      doc.fillColor('#3F3F46').fontSize(11);
      doc.text(`Total Events: ${data.totalEvents}`);
      doc.text(`Total Registrations: ${data.totalRegistrations}`);
      doc.text(`Total Users: ${data.totalUsers}`);
      doc.text(`Active Events: ${data.activeEvents}`);
      
      doc.moveDown(1);
      doc.fillColor('#27272A').fontSize(14).text('Events by Status');
      doc.moveDown(0.3);
      doc.fillColor('#3F3F46').fontSize(10);
      if (data.eventsByStatus) {
        Object.entries(data.eventsByStatus).forEach(([status, count]) => {
          doc.text(`${status}: ${count}`);
        });
      }
      
      doc.moveDown(1);
      doc.fillColor('#27272A').fontSize(14).text('Top Events');
      doc.moveDown(0.3);
      if (data.topEvents) {
        data.topEvents.forEach((event, i) => {
          doc.fillColor('#3F3F46').fontSize(10).text(`${i + 1}. ${event.title} - ${event.currentRegistrations} registrations`);
        });
      }
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
